INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '오늘 해야 할 일을 적어보세요!');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '할일을 클릭하면 완료상태가 됩니다.');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '완료된 할일을 누르면 다시 이전 상태로 돌아갑니다.');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '✘를 누르면 할일이 삭제됩니다.');

INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '청소하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '빨래하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NEVER', '공부하기');
INSERT INTO TODO_ITEM (created_at, updated_at, status, title) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'DONE', '게임하기');